set_property SRC_FILE_INFO {cfile:D:/programming/Xilinx/Vivado/2020.1/my/divclk/divclk.srcs/constrs_1/new/con_divclk.xdc rfile:../../../divclk.srcs/constrs_1/new/con_divclk.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {divclk}]
